### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by jaszfalvitamas** [lodev09/php-models#3]
Hi,
Is it possible to use your model class with transactions? I imagine something like:
$sql->begin_transaction()
$sql->run(), $sql->update(), etc..
$sql->commit()
It would be really nice!

**Comment by lodev09** [comment]
the `DB` class extends `PDO` so you can access normal PDO methods e.g. transactions. The `Model::$db` object represents that class.

So in your model, you'll do something like this:
```php
Model::$db->beginTransaction();
// do normal things here
Model::$db->commit();
```
