### ISSUE TITLE
ahh it looks like PHP 8 is throwing that error only. Please remove `query` then use `run` (alternative) instead. This wrapper class does not officially support php 8 atm. Thanks!

### ISSUE THREAD

**Issue by ER1CK122** [lodev09/php-models#5]
ahh it looks like PHP 8 is throwing that error only. Please remove `query` then use `run` (alternative) instead. This wrapper class does not officially support php 8 atm. Thanks!

_Originally posted by @lodev09 in https://github.com/lodev09/php-models/issues/4#issuecomment-757511021_

**Comment by lodev09** [comment]
PHP 8 is supported for awhile now :)
